# Generated by Django 2.2.5 on 2019-09-12 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('postID', models.AutoField(db_column='postID', primary_key=True, serialize=False)),
                ('dateOfPost', models.DateField()),
                ('postTitle', models.CharField(max_length=35)),
                ('postText', models.CharField(max_length=255)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Posts',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tagID', models.AutoField(db_column='tagID', primary_key=True, serialize=False)),
                ('tagName', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Tags',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Tagmap',
            fields=[
                ('tagmapID', models.AutoField(db_column='tagmapID', primary_key=True, serialize=False)),
                ('postID', models.ForeignKey(db_column='postID', on_delete=django.db.models.deletion.CASCADE, to='tellings.Posts')),
                ('tagID', models.ForeignKey(db_column='tagID', on_delete=django.db.models.deletion.CASCADE, to='tellings.Tags')),
            ],
            options={
                'verbose_name': 'Tagmap',
                'verbose_name_plural': 'Tagmaps',
            },
        ),
    ]
