# Generated by Django 2.2.9 on 2020-01-15 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_date', models.DateField()),
                ('deleted_reason', models.CharField(max_length=15)),
                ('membership_length', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'DeletedAccounts',
                'verbose_name': 'DeletedAccount',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagID', models.AutoField(db_column='tagID', primary_key=True, serialize=False)),
                ('tagName', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Tags',
                'ordering': ['tagName'],
                'verbose_name': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('postID', models.AutoField(db_column='postID', primary_key=True, serialize=False)),
                ('dateOfPost', models.DateField()),
                ('postTitle', models.CharField(max_length=35, unique=True)),
                ('postText', models.CharField(max_length=255)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'UserPosts',
                'verbose_name': 'UserPost',
            },
        ),
        migrations.CreateModel(
            name='Tagmap',
            fields=[
                ('tagmapID', models.AutoField(db_column='tagmapID', primary_key=True, serialize=False)),
                ('postID', models.ForeignKey(db_column='postID', on_delete=django.db.models.deletion.CASCADE, to='tellings.UserPost')),
                ('tagID', models.ForeignKey(db_column='tagID', on_delete=django.db.models.deletion.CASCADE, to='tellings.Tag')),
            ],
            options={
                'verbose_name_plural': 'Tagmaps',
                'verbose_name': 'Tagmap',
            },
        ),
    ]
