# Generated by Django 2.2.10 on 2020-02-28 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tellings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hideFrom', models.ForeignKey(db_column='hideFrom', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('postID', models.ForeignKey(db_column='postID', on_delete=django.db.models.deletion.CASCADE, to='tellings.UserPost')),
            ],
            options={
                'verbose_name_plural': 'HiddenPosts',
                'verbose_name': 'HiddenPost',
            },
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockedBy', models.ForeignKey(db_column='blockedBy', on_delete=django.db.models.deletion.CASCADE, related_name='blockedby_blockeduser_set', to=settings.AUTH_USER_MODEL)),
                ('blockedUser', models.ForeignKey(db_column='blockedUser', on_delete=django.db.models.deletion.CASCADE, related_name='blockeduser_blockeduser_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'BlockedUsers',
                'verbose_name': 'BlockedUser',
            },
        ),
    ]
