# Generated by Django 2.2.5 on 2019-09-16 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tellings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['tagName'], 'verbose_name': 'Tags', 'verbose_name_plural': 'Tags'},
        ),
    ]
