# Generated by Django 2.2.9 on 2020-01-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='dateOfEdit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpost',
            name='isEdited',
            field=models.BooleanField(default=False),
        ),
    ]
