# Generated by Django 2.2.10 on 2020-03-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tellings', '0002_blockeduser_hiddenpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='postTitle',
            field=models.CharField(max_length=35),
        ),
    ]
