# Generated by Django 2.2.9 on 2020-01-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tellings', '0002_auto_20200128_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='isEdited',
        ),
    ]
