# Generated by Django 2.2.10 on 2020-03-15 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tellings', '0003_auto_20200307_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagmap',
            name='postID',
        ),
        migrations.RemoveField(
            model_name='tagmap',
            name='tagID',
        ),
        migrations.AddField(
            model_name='tagmap',
            name='post',
            field=models.ForeignKey(db_column='post', default=1, on_delete=django.db.models.deletion.CASCADE, to='tellings.UserPost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tagmap',
            name='tag',
            field=models.ForeignKey(db_column='tag', default=1, on_delete=django.db.models.deletion.CASCADE, to='tellings.Tag'),
            preserve_default=False,
        ),
    ]
