# Generated by Django 2.2.9 on 2020-02-07 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tellings', '0003_remove_userpost_isedited'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('commentID', models.AutoField(db_column='commentID', primary_key=True, serialize=False)),
                ('dateOfComment', models.DateField()),
                ('commentText', models.CharField(max_length=255)),
                ('dateOfEdit', models.DateField(blank=True, null=True)),
                ('postID', models.ForeignKey(db_column='postID', on_delete=django.db.models.deletion.CASCADE, to='tellings.UserPost')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserComment',
                'verbose_name_plural': 'UserComments',
            },
        ),
    ]
