"""
# Filename:     page_extras.py
# Author:       Andrew Laing
# Email:        parisianconnections@gmail.com
# Last Updated: 05/01/2020
# Description:  Extra data used on the pages.
#               At present this contains the random quotes used in the header of each page.
"""

random_quotes = [
    "\"I am no bird; and no net ensnares me: I am a free human being with an independent will.\" - Charlotte Brontë",
    "\"Lock up your libraries if you like; but there is no gate, no lock, no bolt that you can set upon the freedom of my mind.\" ― Virginia Woolf",
    "\"When a man is denied the right to live the life he believes in, he has no choice but to become an outlaw.\" ― Nelson Mandela", 
    "\"People demand freedom of speech as a compensation for the freedom of thought which they seldom use.\" ― Soren Kierkegaard",
    "\"The unhappiest people in this world, are those who care the most about what other people think.\" ― C. JoyBell C.", 
    "\"If we don't believe in freedom of expression for people we despise, we don't believe in it at all.\" ― Noam Chomsky", 
    "\"We must be free not because we claim freedom, but because we practice it.\" ― William Faulkner",
    "\"The first duty of a man is to think for himself.\" ― Jose Marti", 
    "\"Whenever I hear anyone arguing for slavery, I feel a strong impulse to see it tried on him personally.\" ― Abraham Lincoln", 
    "\"Freedom is what we do with what is done to us.\" ― Jean-Paul Sartre", 
    "\"Who is more to be pitied, a writer bound and gagged by policemen or one living in perfect freedom who has nothing more to say?\" ― Kurt Vonnegut", 
    "\"Democracy must be something more than two wolves and a sheep voting on what to have for dinner.\" ― James Bovard",
    "\"If freedom of speech is taken away, then dumb and silent we may be led, like sheep to the slaughter.\" ― George Washington", 
    "\"Those who will not reason, are bigots, those who cannot, are fools, and those who dare not, are slaves.\" ― Byron", 
    "\"Hypocrites get offended by the truth.\" ― Jess C. Scott",
    "\"Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control.\" ― Epictetus", 
    "\"A Nation should not be judged by how it treats its highest citizens, but it's lowest ones.\" ― Nelson Mandela",
    "\"The price of freedom is eternal vigilance.\" ― John Philpot Curran", 
    "\"The advancement and diffusion of knowledge is the only guardian of true liberty.\" ― James Madison", 
    "\"Secrecy begets tyranny.\" ― Robert A. Heinlein",
    "\"Free election of masters does not abolish the masters or the slaves.\" ― Herbert Marcuse", 
    "\"Slaves are generally expected to sing as well as to work.\" ― Frederick Douglass", 
    "\"Whoever would overthrow the liberty of a nation must begin by subduing the freeness of speech.\" ― Benjamin Franklin",
    "\"It’s not unpatriotic to denounce an injustice committed on our behalf, perhaps it’s the most patriotic thing we can do.\" ― E.A. Bucchianeri",
    "\"Ignorance is ultimately the worst enemy of a people who want to be free.\" ― Jonathan Hennessey",
    "\"Cinema, radio, television, magazines are a school of inattention: people look without seeing, listen in without hearing\" ― Robert Bresson",  
    "\"If it’s true that nothing is more potent than an idea, then those who control the media can direct minds en masse.\" ― Lance Morcan",
    "\"It’s becoming obvious to most that mainstream media is nothing but a megaphone for the global elite to present biased news that’s designed to align the masses with their agenda.\" ― James Morcan",
    "\"Protesters should make their own media and not rely on mainstream media to cover them.\" - Naomi Wolf",
    "\"One believes things because one has been conditioned to believe them.\" ― Aldous Huxley",
    "\"Since the earliest days of our youth, we have been conditioned to accept that the direction of the herd, and authority anywhere — is always right.\" ― Suzy Kassem",
    "\"The only thing deterring us from complete free will is our social conditioning which influences our thoughts and decision-making.\" ― Rajesh",
    "\"One free act is often enough to dispel a lifetime of conditioning.\" ― Marty Rubin",
]


banned_words = [
    '2g1c', '2 girls 1 cup', 'abba-dabba', 'abi-dabi', 'acrotomophilia', 'alabama hot pocket', 
    'alaskan pipeline', 'anal', 'anilingus', 'anus', 'apeshit', 'arse', 'arsehole', 'aryan', 
    'auto erotic', 'autoerotic', 'baby batter', 'baby juice', 
    'bacon', 'ball gag', 'ball gravy', 'ball kicking', 'ball licking', 'ball sack', 'ball sucking', 
    'bamboola', 'bangbros', 'bareback', 'barely legal', 'bastard', 'beaner', 'beaver cleaver', 
    'beaver lips', 'bestiality', 'biatch', 'big breasts', 'big knockers', 
    'bimbos', 'birdlock', 'bitch', 'bitches', 'black cock', 'blonde action', 
    'blonde on blonde action', 'blowjob', 'blow job', 'blow your load', 'blue waffle', 
    'blumpkin', 'bollock', 'bollok', 'boob', 'booty call', 'brown showers', 'brunette action', 
    'bukkake', 'bulldyke', 'bullet vibe', 'bullshit', 'bung hole', 'bunghole', 'busty', 
    'butt', 'buttcheeks', 'butthole', 'camel toe', 'camgirl', 'camslut', 'camwhore', 'carpet muncher', 
    'carpetmuncher', 'carrot top', 'cheesehead', 'chocolate rosebuds', 'christ', 
    'cleveland steamer', 'clit', 'clitoris', 'clover clamps', 'cock', 'cornhole', 'coon', 
    'creampie', 'cum', 'cumming', 'cunnilingus', 'cunt', 'darkie', 'daterape', 'deep throat', 
    'deepthroat', 'dendrophilia', 'dick', 'dildo', 'dingleberry', 'dingleberries', 'dirty pillows', 
    'dirty sanchez', 'doggie style', 'doggiestyle', 'doggy style', 'doggystyle', 'dog style', 'donkey punch', 
    'double dong', 'double penetration', 'dp action', 'dry hump', 'eat my ass', 'ejaculation', 'eunuch', 'fecal', 
    'feck', 'felch', 'fellate', 'fellatio', 'feltch', 'female squirting', 'femdom', 'figging', 'fingerbang', 
    'fingering', 'fisting', 'foot fetish', 'footjob', 'frotting', 'fuck', 'f u c k', 'fudge packer', 'fudgepacker', 
    'gang bang', 'gay sex', 'giant cock', 'ginger', 'girls gone wild', 'goatcx', 'goatse', 
    'golden shower', 'goodpoop', 'goo girl', 'goregasm', 'grope', 'group sex', 'hand job', 'handjob', 
    'hard core', 'hardcore', 'hentai', 'homoerotic', 'honkey', 'hooker', 'hot carl', 'how to kill', 
    'how to murder', 'huge fat', 'humping', 'incest', 'jack off', 'jail bait', 'jailbait', 
    'jerk off', 'jigaboo', 'jiggaboo', 'jiggerboo', 'jizz', 'juggs', 'kike', 'knobbing', 'knobend', 
    'knob end', 'lemon party', 'lolita', 'lovemaking', 'make me come', 'male squirting', 'masturbate', 
    'menage a trois', 'missionary position', 'motherfucker', 'mound of venus', 'mr hands', 'muff', 'nambla', 
    'nawashi', 'negro', 'nigga', 'nigger', 'nig nog', 'nipple', 
    'nympho', 'nymphomania', 'octopussy', 'omorashi', 'one cup two girls', 'one guy one jar', 
    'orgasm', 'orgy', 'paedophile', 'panties', 'panty', 'pedobear', 'pedophile', 'pegging', 
    'phone sex', 'piece of shit', 'pikey', 'pleasure chest', 'pole smoker', 'ponyplay', 'poof', 'poon', 
    'poontang', 'poop chute', 'poopchute', 'pubes', 'pussy', 'queaf', 'queef', 'quim', 'rag head', 
    'raghead', 'raging boner', 'rectum', 'reverse cowgirl', 'rimjob', 'rimming', 'rosy palm', 
    'rusty trombone', 'santorum', 'scat', 'schlong', 'scissoring', 'scrotum', 'semen', 
    'shaved beaver', 'shaved pussy', 'sheep shag', 'shit', 's hit', 'sh1t', 'shota', 'shrimping', 'skeet', 
    'slanteye', 'slut', 's&m', 'smut', 'snatch', 'snowballing', 'sodomize', 'sodomy', 'spic', 
    'splooge', 'spooge', 'spread legs', 'spunk', 'strap on', 'strapon', 'strappado', 
    'strip club', 'style doggy', 'sultry women', 'swastika', 'tea bagging', 
    'threesome', 'throating', 'tight white', 'titties', 'titty', 'tongue in a', 'tosser', 'towelhead', 
    'tranny', 'tribadism', 'tub girl', 'tubgirl', 'turd', 'tushy', 'twat', 'two girls one cup', 
    'upskirt', 'up the bum', 'urethra play', 'urophilia', 'vagina', 'venus mound', 'vibrator', 'violet wand', 
    'wank', 'wetback', 'white power', 'whore', 'wrinkled starfish', 'yellow showers', 'zoophilia'
]
